
services:
  api:
    image: donkeyhott/ekbtrees-api:latest
    environment:
      DATASOURCE_URL: "${DATASOURCE_URL}"
      DATASOURCE_LOGIN: "${DATASOURCE_LOGIN}"
      DATASOURCE_PASSWORD: "${DATASOURCE_PASSWORD}"
      DDL_AUTO: "none"
      S3_HOST: "${S3_HOST}"
      S3_REGION: "${S3_REGION}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
      ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN_SECRET}"
      VK_APP_ID: "${VK_APP_ID}"
      VK_APP_SECRET_KEY: "${VK_APP_SECRET_KEY}"
      FB_APP_ID: "${FB_APP_ID}"
      FB_APP_SECRET_KEY: "${FB_APP_SECRET_KEY}"
      BASE_URL: "https://ekb-trees-help.ru"
      ACCESS_TOKEN_LIFESPAN: "${ACCESS_TOKEN_LIFESPAN}"
      REFRESH_TOKEN_LIFESPAN: "${REFRESH_TOKEN_LIFESPAN}"
      REFRESH_TOKEN_SECRET: "${REFRESH_TOKEN_SECRET}"
      PASSWORDS_SALT: "${PASSWORDS_SALT}"
      SUPERUSER_PASSWORD: "${SUPERUSER_PASSWORD}"
    ports:
      - "8080:8080"
