version: "3.9"
services:
  api:
    image: donkeyhott/ekbtrees-api:latest
    environment:
      DATASOURCE_URL: "${DATASOURCE_URL}"
      DATASOURCE_LOGIN: "${DATASOURCE_LOGIN}"
      DATASOURCE_PASSWORD: "${DATASOURCE_PASSWORD}"
      DDL_AUTO: "none"
      S3_HOST: "${S3_HOST}"
      S3_REGION: "${S3_REGION}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
      ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN_SECRET}"
    ports:
      - "8080:8080"
